grant connect to om;
grant select on DBA_DATA_FILES to om;
grant select on DBA_FREE_SPACE to om;
grant select on DBA_INDEXES to om;
grant select on DBA_IND_PARTITIONS to om;
grant select on DBA_ROLE_PRIVS to om;
grant select on DBA_ROLES to om;
grant select on DBA_SEGMENTS to om;
grant select on DBA_OBJECTS to om;
grant select on DBA_SYS_PRIVS to om;
grant select on DBA_TABLESPACES to om;
grant select on DBA_TAB_PARTITIONS to om;
grant select on DBA_TAB_PRIVS to om;
grant select on DBA_TEMP_FILES to om;
grant select on DBA_USERS to om;
grant select on sys.V_$CONTROLFILE to om;
grant select on sys.V_$LOG to om;
grant select on sys.V_$LOGFILE to om;
grant select on sys.V_$DATAFILE to om;
grant select on sys.V_$TEMPFILE to om;
grant select on sys.V_$INSTANCE to om;
grant select on sys.v_$parameter to om;
grant select on sys.v_$session to om;
grant alter database to om;
grant alter tablespace to om;
grant create tablespace to om;
grant create user to om;
grant alter user to om;
grant alter system to om;
grant create any table to om;
grant create any index to om;
grant alter any table to om;
grant alter any index to om;
grant alter any procedure to om;
grant alter any trigger to om;
grant alter system to om;

