
host kill -9 11967                                                                        
host kill -9 27019                                                                        
host kill -9 29323                                                                        
host kill -9 5444                                                                         
host kill -9 5473                                                                         
host kill -9 20828                                                                        
host kill -9 24002                                                                        
host kill -9 4369                                                                         
host kill -9 25644                                                                        
host kill -9 9938                                                                         
host kill -9 74                                                                           
host kill -9 23389                                                                        
host kill -9 26938                                                                        
host kill -9 17403                                                                        
host kill -9 25421                                                                        
host kill -9 13811                                                                        
host kill -9 23946                                                                        
host kill -9 16245                                                                        
host kill -9 28850                                                                        
host kill -9 4631                                                                         
host kill -9 17482                                                                        
host kill -9 24687                                                                        
host kill -9 18632                                                                        
host kill -9 2564                                                                         
host kill -9 1053                                                                         
host kill -9 16506                                                                        
host kill -9 25777                                                                        
host kill -9 7316                                                                         
